from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from grif.models.enums import (
    TaskType,
    ToolCategory,
    WakeTriggerType,
)


class ModelConfig(BaseModel):
    """Per-agent LLM settings."""

    model_id: str = "claude-sonnet-4-6"
    temperature: float = Field(default=0.3, ge=0.0, le=2.0)
    max_tokens: int = Field(default=4096, ge=1)
    provider: str = "anthropic"


class WakeTrigger(BaseModel):
    """Condition that will wake a SLEEPING agent."""

    trigger_type: WakeTriggerType
    # For SCHEDULE: cron expression, e.g. "0 9 * * 1-5"
    # For CONDITION: JSON path + operator + threshold, e.g. {"path": "price", "op": "<", "value": 5000}
    # For EVENT: event name / webhook path
    condition: str | None = None
    value: Any = None


class Schedule(BaseModel):
    """Cron-based schedule for RECURRING agents."""

    cron_expression: str = Field(
        description="Standard cron expression: '0 9 * * *' = daily at 09:00",
        examples=["0 9 * * *", "0 18 * * 5"],
    )
    timezone: str = Field(default="UTC")


class CommunicationConfig(BaseModel):
    """Language settings for Multi-Language Orchestration."""

    language: str = Field(
        default="ru",
        description="Output language for the agent (BCP-47). Corresponds to user's language.",
    )
    search_languages: list[str] = Field(
        default_factory=lambda: ["en"],
        description="Languages to search sources in. Can differ from output language.",
    )


class ToolPermission(BaseModel):
    """Per-tool trust state for a specific agent."""

    tool_name: str
    category: ToolCategory
    auto_approved: bool = False
    approval_count: int = 0  # Times user explicitly approved
    trust_threshold: int = 5  # Approvals needed to go auto (WRITE_PUBLIC only)


class PromptLayers(BaseModel):
    """
    4-layer prompt architecture.
    Layer 1: CoreIdentity — hardcoded in templates/core_identity.yaml
    Layer 2: RoleTemplate — from blueprint YAML
    Layer 3: TaskContext — LLM-generated from StructuredIntent
    Layer 4: UserPersona — User Profile + Style Guide + Inherited Memory
    """

    layer_1_core_identity: str
    layer_2_role_template: str
    layer_3_task_context: str
    layer_4_user_persona: str = ""

    def assemble(self) -> str:
        parts = [
            self.layer_1_core_identity,
            self.layer_2_role_template,
            self.layer_3_task_context,
        ]
        if self.layer_4_user_persona:
            parts.append(self.layer_4_user_persona)
        return "\n\n---\n\n".join(p.strip() for p in parts if p.strip())


class AgentConfig(BaseModel):
    """
    Complete configuration for one agent instance.
    Generated by pipeline/config_generator.py (Step 5).
    """

    id: UUID = Field(default_factory=uuid4)
    user_id: str
    task_type: TaskType
    blueprint_id: str | None = None

    # System prompt assembled from 4 layers
    prompt_layers: PromptLayers
    system_prompt: str = ""  # Assembled from prompt_layers at spawn time

    # Tools this agent is allowed to use
    tools: list[str] = Field(default_factory=list)
    tool_permissions: list[ToolPermission] = Field(default_factory=list)

    model_config_: ModelConfig = Field(
        default_factory=ModelConfig,
        alias="model_config",
    )

    # For SLEEPING agents: conditions that will wake them
    wake_triggers: list[WakeTrigger] = Field(default_factory=list)

    # For RECURRING agents: execution schedule
    schedule: Schedule | None = None

    communication: CommunicationConfig = Field(
        default_factory=CommunicationConfig
    )

    # Parent agent UUID for FORK lineage tracking
    parent_agent_id: UUID | None = None

    # Extra metadata passed through from StructuredIntent
    metadata: dict[str, Any] = Field(default_factory=dict)

    model_config = {"populate_by_name": True}

    def get_model_config(self) -> ModelConfig:
        return self.model_config_
